name: DevOps Intern CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Docker Compose
        run: docker compose up --build --abort-on-container-exit
        continue-on-error: true

      - name: Handle Success
        if: success()
        run: echo "Tests passed!" > succeeded.txt

      - name: Upload Success Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: succeeded
          path: succeeded.txt

      - name: Handle Failure
        if: failure()
        run: echo "Tests failed." > fail.txt

      - name: Upload Failure Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fail
          path: fail.txt
